name: Build Windows EXE

on:
  push:
    branches: [ "master" ]
  workflow_dispatch: # Позволяет запускать сборку вручную через кнопку на сайте

jobs:
  build:
    runs-on: windows-latest

    steps:
    # 1. Скачиваем код репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Устанавливаем Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10' # Укажите версию Python, которую используете в проекте
        cache: 'pip'

    # 3. Устанавливаем зависимости
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # Устанавливаем Nuitka и zstandard (для лучшего сжатия)
        pip install nuitka zstandard
        # Устанавливаем зависимости проекта
        if (Test-Path requirements.txt) { pip install -r requirements.txt }

    # 4. Компиляция (Ваша команда)
    - name: Build with Nuitka
      run: |
        python -m nuitka --onefile --assume-yes-for-downloads --enable-plugin=pyqt6 --windows-console-mode=disable --include-data-dir=squig2proq\data=data squig2proq

    # 5. Сохраняем результат (Upload Artifact)
    # Этот шаг найдет все .exe файлы в корне и загрузит их в артефакты сборки
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Exe
        path: '*.exe'
        retention-days: 5